"""Add volume to Fv.

Revision ID: 20fd511223e8
Revises: 46fffc983949
Create Date: 2020-09-24 22:01:47.071154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20fd511223e8'
down_revision = '46fffc983949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Fv', sa.Column('Volume', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Fv', 'Volume')
    # ### end Alembic commands ###
