"""Add Gravity table.

Revision ID: 2d6346c813d6
Revises: 20fd511223e8
Create Date: 2020-09-24 22:06:59.837131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d6346c813d6'
down_revision = '20fd511223e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Gravity',
    sa.Column('GravityId', sa.Integer(), nullable=False),
    sa.Column('FvId', sa.Integer(), nullable=False),
    sa.Column('Gravity', sa.Float(), nullable=False),
    sa.Column('Timestamp', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['FvId'], ['Fv.FvId'], ),
    sa.PrimaryKeyConstraint('GravityId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Gravity')
    # ### end Alembic commands ###
